import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

/**
 * Wiki content collection.
 *
 * Articles live at src/content/wiki/<locale>/<contentType>/<slug>.mdx
 * The `id` generated by the glob loader is the path relative to base, without extension,
 * e.g. "en/bosses/emberfang".
 *
 * Frontmatter is validated at build time by the Zod schema below. A missing or
 * malformed field fails the build immediately.
 *
 * `image` uses the `image()` helper so covers are processed by Astro Image
 * (auto WebP/AVIF + responsive srcset). Frontmatter value is a path relative
 * to the MDX file, e.g. `image: '../../../assets/covers/emberfang-cover.svg'`.
 * At build time `entry.data.image` is `ImageMetadata | undefined`. For an
 * absolute og:image URL, read `.src` and prefix with `siteUrl`.
 */
const wiki = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/wiki' }),
  schema: ({ image }) =>
    z.object({
      title: z.string().max(80),
      description: z.string().min(40).max(165),
      category: z.string(),
      date: z.coerce.date(),
      lastModified: z.coerce.date().optional(),
      /** Maximum age of the latest verification before the stale notice appears. */
      refreshAfterDays: z.number().int().positive().max(365).optional(),
      image: image().optional(),
      tags: z.array(z.string()).default([]),
      noindex: z.boolean().default(false),
      /**
       * Draft articles: visible in `pnpm dev`, excluded from the production
       * build (pages, lists, recent, related, hreflang, sitemap).
       */
      draft: z.boolean().default(false),
      /**
       * Game version this article applies to (e.g. "v2.5"). Rendered as a
       * badge on the article header — a freshness/E-E-A-T signal for
       * fast-patching games. Optional.
       */
      gameVersion: z.string().max(20).optional(),
      /** Quick-answer summary shown before the article body (AI Overviews / featured snippet). */
      summary: z.string().max(200).optional(),
      /** Named person credited for this article. Missing authors use the site Organization. */
      author: z.string().optional(),
      /**
       * Optional structured boss stats — rendered as a scannable data card
       * (BossStatCard) above the article body. Values are strings so authors
       * can express nuance ("4200 (Phase 2: 6300)").
       */
      boss: z
        .object({
          hp: z.string(),
          weakness: z.string(),
          resistant: z.string(),
          location: z.string(),
          recommendedLevel: z.string().optional(),
        })
        .optional(),
      /**
       * Optional related YouTube video IDs (lazy-loaded embeds at the article
       * bottom — zero JS until click). 11-char IDs, not full URLs.
       */
      videos: z.array(z.string()).optional(),
      /**
       * Optional image gallery — rendered as a thumbnail grid below the
       * article body with a native <dialog> lightbox (zero JS until click).
       * `image` is a path relative to the MDX file (same as the cover).
       */
      gallery: z
        .array(
          z.object({
            image: image(),
            caption: z.string().max(200).optional(),
            alt: z.string().max(200).optional(),
          }),
        )
        .default([]),
      /**
       * Structured redeem codes (codes pages). Rendered as a CodesTable
       * above the article body: Active section (CodeBlock, one-click copy)
       * + Expired section (table, long-tail SEO for "is X still working").
       * `status` drives the split; `expiryDate`/`source` are freshness and
       * E-E-A-T signals. Body stays for prose (how to redeem, reward notes).
       */
      codes: z
        .array(
          z.object({
            code: z.string().min(1),
            reward: z.string().optional(),
            status: z.enum(['active', 'expired']).default('active'),
            expiryDate: z.string().max(40).optional(),
            source: z.string().optional(),
          }),
        )
        .optional(),
    }),
});

/**
 * Handbook collection — the in-site documentation center at /landing/docs
 * (+ /zh/landing/docs). Chapters live OUTSIDE src/content on purpose: the
 * markdown under docs/handbook/ is the single source of truth, browsable on
 * GitHub, and **survives `pnpm apply-template`** (the learning manual's SOPs
 * and AI prompts are directly useful to fork users) — only the landing ROUTES
 * are removed by the CLI.
 *
 * Files: docs/handbook/<locale>/<slug>.md → id "en/<slug>" / "zh/<slug>".
 * zh chapters MUST reuse the same ASCII slug as their en counterpart —
 * CJK filenames percent-encode in URLs, and 1:1 slug pairing makes the
 * en/zh parity test (tests/handbook.test.ts) trivial.
 *
 * Plain .md (not .mdx): handbooks are static prose + code blocks; they do not
 * use the wiki component vocabulary.
 */
const handbook = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './docs/handbook' }),
  schema: z.object({
    title: z.string().max(80),
    description: z.string().min(40).max(165),
    /** Which manual the chapter belongs to (drives hub grouping + prev/next scope). */
    manual: z.enum(['learn', 'dev']),
    /** Position within the manual (1-based, unique per manual). */
    order: z.number().int(),
    icon: z.string().default('lucide:book-open'),
    /**
     * 40–60 word direct answer, rendered as the TL;DR card (AI Overviews
     * candidate). 480 chars ≈ 60-70 English words — zh lands well under,
     * en translations run longer per word.
     */
    tldr: z.string().max(480).optional(),
    /** Last content review — feeds the sitemap lastmod scan (astro.config.ts). */
    updated: z.coerce.date().optional(),
  }),
});

export const collections = { wiki, handbook };
